### ISSUE TITLE
生态邀请

### ISSUE THREAD

**Issue by yt605155624** [EscaticZheng/ps3.9wheel-install#1]
- 可以新增一个 requirements.txt 里面写上 paddlespeech 这样就能在 PaddleSpeech 仓库右侧 **Used by** 里面看到你这个仓库
- 可以给 PaddleSpeech repo 提交一个 readme 的修改，参考 https://github.com/PaddlePaddle/PaddleSpeech/pull/2688/files

**Comment by EscaticZheng** [comment]
已经上传requirements.txt，可以看到了
请问readme是具体修改什么呢？是和这个链接一样添加many thanks的内容吗

**Comment by yt605155624** [comment]
是的，中文和英文 readme 都要加上，提交代码参考 
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2325

**Comment by EscaticZheng** [comment]
ci 一直过不了，请问该怎么办，，

**Comment by yt605155624** [comment]
你好，CI 我来负责跑通，您把 CLA 签署好即可，不用重复提交 pr，可以把之前的 reopen 一下签署好 CLA 即可

**Comment by EscaticZheng** [comment]
> 你好，CI 我来负责跑通，您把 CLA 签署好即可，不用重复提交 pr，可以把之前的 reopen 一下签署好 CLA 即可

已经签了CLA，不过那个https://github.com/PaddlePaddle/PaddleSpeech/pull/2912 我这显示没法reopen。

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/pull/2915 我 reopen 这个了，ci 过后我会合入

**Comment by EscaticZheng** [comment]
> [PaddlePaddle/PaddleSpeech#2915](https://github.com/PaddlePaddle/PaddleSpeech/pull/2915) 我 reopen 这个了，ci 过后我会合入

谢谢，第一次这样给开源做贡献，不是很懂，麻烦你了
